name: 'extensions'

on:
    repository_dispatch:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'

            -   name: build xml
                run: php extensions.php

            -   uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Apply automatic changes
